from typing import List, Optional, ClassVar

class Device:
    CPU: ClassVar['Device']
    CUDA: ClassVar['Device']
    def __init__(self, value: int) -> None: ...

class DType:
    Int32: ClassVar['Device']
    Float32: ClassVar['Device']
    def __init__(self, value: int) -> None: ...

class Tensor:
    shape: List[int]
    strides: List[int]
    size: int
    device: Device
    data_ptr: int

    def __init__(self, shape: List[int], device: Device = Device.CUDA) -> None: ...

    def to_cuda(self) -> Tensor: ...
    def to_cpu(self) -> Tensor: ...

    def reshape(shape) -> None: ...
    
    def add(self, other: Tensor) -> Tensor: ...
    
    def mul(self, other: Tensor) -> Tensor: ...
    
    def matmul(self, other: Tensor, trans_a=False, trans_b=False) -> Tensor: ...

    def silu(self, out: Optional[Tensor] = None) -> Tensor: ...

    def softmax(self, out: Optional[Tensor] = None) -> Tensor: ...

    def embedding(idx: Tensor, weight: Tensor, out: Optional[Tensor] = None) -> Tensor: ...

    def rope(q: Tensor, k: Tensor, cos: Tensor, sin: Tensor, start_pos: int) -> None: ...

    def kv_cache_update(k_cache: Tensor, v_cache: Tensor, k_src: Tensor, v_src: Tensor, start_pos: int) -> None: ...
        
    def __repr__(self) -> str: ...

